use crate::bible_ref_utils::BOOK_NAMES;

#[derive(Hash, Copy, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum Book {
    Genesis = 1,
    Exodus = 2,
    Leviticus = 3,
    Numbers = 4,
    Deuteronomy = 5,
    Joshua = 6,
    Judges = 7,
    Ruth = 8,
    FirstSamuel = 9,
    SecondSamuel = 10,
    FirstKings = 11,
    SecondKings = 12,
    FirstChronicles = 13,
    SecondChronicles = 14,
    Ezra = 15,
    Nehemiah = 16,
    Esther = 17,
    Job = 18,
    Psalms = 19,
    Proverbs = 20,
    Ecclesiastes = 21,
    SongOfSolomon = 22,
    Isaiah = 23,
    Jeremiah = 24,
    Lamentations = 25,
    Ezekiel = 26,
    Daniel = 27,
    Hosea = 28,
    Joel = 29,
    Amos = 30,
    Obadiah = 31,
    Jonah = 32,
    Micah = 33,
    Nahum = 34,
    Habakkuk = 35,
    Zephaniah = 36,
    Haggai = 37,
    Zechariah = 38,
    Malachi = 39,
    Matthew = 40,
    Mark = 41,
    Luke = 42,
    John = 43,
    Acts = 44,
    Romans = 45,
    FirstCorinthians = 46,
    SecondCorinthians = 47,
    Galatians = 48,
    Ephesians = 49,
    Philippians = 50,
    Colossians = 51,
    FirstThessalonians = 52,
    SecondThessalonians = 53,
    FirstTimothy = 54,
    SecondTimothy = 55,
    Titus = 56,
    Philemon = 57,
    Hebrews = 58,
    James = 59,
    FirstPeter = 60,
    SecondPeter = 61,
    FirstJohn = 62,
    SecondJohn = 63,
    ThirdJohn = 64,
    Jude = 65,
    Revelation = 66
}

impl Book {
    pub fn name(&self) -> &str {
        &BOOK_NAMES[*self as usize - 1]
    }
}